-- This file should undo anything in `up.sql`
-- Your SQL goes here
DROP TABLE DAILY_STATS;

DROP TABLE WEEKLY_STATS;

DROP TABLE ALL_TIME_STATS;

DROP TABLE NAMES;

DROP TABLE GAME_NUMBER;

DROP TABLE WEEK_NUMBER;

DROP TABLE PLAYER_RATINGS;