-- This file should undo anything in `up.sql`
-- Your SQL goes here
DROP TABLE IF EXISTS DAILY_STATS;

DROP TABLE IF EXISTS WEEKLY_STATS;

DROP TABLE IF EXISTS ALL_TIME_STATS;

DROP TABLE IF EXISTS NAMES;

DROP TABLE IF EXISTS GAME_NUMBER;

DROP TABLE IF EXISTS WEEK_NUMBER;

DROP TABLE IF EXISTS PLAYER_RATINGS;