-- Your SQL goes here
CREATE TABLE IF NOT EXISTS DAILY_STATS
(PLAYER_ID TEXT PRIMARY KEY NOT NULL,
SCORE INT NOT_NULL);

CREATE TABLE IF NOT EXISTS WEEKLY_STATS
(PLAYER_ID TEXT PRIMARY KEY NOT NULL,
GAMES_PLAYED INT NOT_NULL,
TOTAL_SCORE INT NOT_NULL,
AVERAGE_SCORE REAL NOT_NULL,
NUM_1S INT DEFAULT 0,
NUM_2S INT DEFAULT 0,
NUM_3S INT DEFAULT 0,
NUM_4S INT DEFAULT 0,
NUM_5S INT DEFAULT 0,
NUM_6S INT DEFAULT 0,
NUM_XS INT DEFAULT 0);

CREATE TABLE IF NOT EXISTS ALL_TIME_STATS
(PLAYER_ID TEXT PRIMARY KEY NOT NULL,
GAMES_PLAYED INT NOT_NULL,
TOTAL_SCORE INT NOT_NULL,
AVERAGE_SCORE REAL NOT_NULL,
NUM_1S INT DEFAULT 0,
NUM_2S INT DEFAULT 0,
NUM_3S INT DEFAULT 0,
NUM_4S INT DEFAULT 0,
NUM_5S INT DEFAULT 0,
NUM_6S INT DEFAULT 0,
NUM_XS INT DEFAULT 0);

CREATE TABLE IF NOT EXISTS NAMES
(PLAYER_ID TEXT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS GAME_NUMBER
(GAME INT PRIMARY KEY NOT NULL);

CREATE TABLE IF NOT EXISTS WEEK_NUMBER
(WEEK INT PRIMARY KEY NOT NULL);

CREATE TABLE IF NOT EXISTS PLAYER_RATINGS
(PLAYER_ID TEXT PRIMARY KEY NOT NULL,
MU REAL NOT_NULL,
SIGMA REAL NOT_NULL);